apiVersion: v1
kind: Service
metadata:
  namespace: dev-expert-pricing
  name: pricing-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:618817091491:certificate/bdc470c9-e382-4f6a-9419-66f5efa73d64"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pricing